package com.digitcreativestudio.dzulfikar68.myrecyclerview;

import java.util.ArrayList;

public class PresidentData {
    public static String[][] data = new String[][]{
            {"Benua ASIA", "benua terbesar ke-1", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Asia_%28orthographic_projection%29.svg/480px-Asia_%28orthographic_projection%29.svg.png", "Asia (Listeni/ˈeɪʒə/ atau /ˈeɪʃə/) adalah benua terbesar dan paling padat penduduknya di dunia, terletak di bagian timur dan belahan utara. Benua ini mencakup 8,7% dari total luas permukaan bumi dan terdiri dari 30% dari luas daratannya. Dengan sekitar 4,3 miliar orang, terdapat 60% dari populasi manusia dunia saat ini. Asia memiliki tingkat pertumbuhan yang tinggi di era modern. Misalnya, selama abad ke-20, Populasi Asia hampir empat kali lipat.[3]\\nBenua Asia dan Eropa merupakan benua yang terhubung lewat darat dan keduanya membentuk suatu benua raksasa yang disebut sebagai Eurasia. Batas antara Asia dan Eropa sangat kabur sehingga beberapa negara seperti Turki terkadang dapat dimasukkan ke Asia maupun Eropa. Beberapa bentang alam yang sering dipakai untuk memisahkan kedua benua tersebut adalah Selat Dardanella, Laut Marmara, Selat Bosporus, Laut Hitam, Pegunungan Kaukasus, Laut Kaspia, Sungai Ural (atau Sungai Emba), dan Pegunungan Ural hingga Novaya Zemlya. Selain berbatasan langsung dengan Benua Eropa, Benua Asia juga memiliki batas langsung dengan Benua Afrika yang memiliki perbatasan darat dan bertemu di sekitar Terusan Suez.\\nMengingat ukuran dan keragamannya, konsep Asia – nama tersebut kembali ke zaman klasik – yang sebenarnya mungkin lebih berkaitan dengan geografi manusia daripada geografi fisik.[4] Asia sangat beragam dan di dalam masing-masing wilayahnya terdapat kelompok-kelompok etnis, budaya, lingkungan, ekonomi, hubungan sejarah dan sistem pemerintahan."},
            {"Benua AMERIKA", "benua terbesar ke-2", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Americas_%28orthographic_projection%29.svg/480px-Americas_%28orthographic_projection%29.svg.png", "Benua Amerika adalah sebuah benua di dunia yang merujuk kepada wilayah daratan di antara Samudra Pasifik dan Samudra Atlantik. Benua Amerika adalah benua terbesar ke 2 di dunia setelah Benua Asia .Luas wilayahnya ± 42.292.000 Km². Benua ini umumnya dibagi menjadi 3 yaitu Amerika Utara, Amerika Tengah, dan Amerika Selatan. Istilah ini juga merujuk kepada wilayah Karibia, pulau-pulau sekitar Laut Karibia, dan Greenland (namun bukan Islandia).Wilayah Amerika Tengah merupakan daratan sempit memanjang yang menghubungkan antara Amerika Utara dan Amerika Selatan. Secara astronomis, Benua Amerika terletak antara 72° LU - 59° LS dan 36° BB - 163° BB. Secara geografis, letak Benua Amerika sebelah Barat berbatasan dengan Samudera Pasifik dan Laut Bering, sebelah timur berbatasan dengan Samudera Atlantik dan Laut Karibia, sebelah utara berbatasan dengan Laut Es dan Selat Davis, dan sebelah selatan berbatasan dengan Laut Kutub Selatan. Nama Amerika diambil dari nama pertama orang Eropa yang menjelajahi benua ini yaitu \"Amerigo Vespucci.\" "},
            {"Benua AFRIKA", "benua terbesar ke-3", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Africa_%28orthographic_projection%29.svg/480px-Africa_%28orthographic_projection%29.svg.png", "Afrika adalah benua terbesar ketiga di dunia setelah Asia dan Amerika (utara dan tengah dan selatan) dan kedua terbanyak penduduknya setelah Asia. Dengan luas wilayah 30.224.050 km² termasuk pulau-pulau yang berdekatan, Afrika meliputi 20,3% dari seluruh total daratan Bumi. Dengan 800 juta penduduk di 54 negara, benua ini merupakan tempat bagi sepertujuh populasi dunia."},
            {"Benua ANTARKTIKA", "benua terbesar ke-4", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Antarctica_%28orthographic_projection%29.svg/481px-Antarctica_%28orthographic_projection%29.svg.png", "Antarktika (Listeni/ænˈtɑːrktᵻkə/ atau /æntˈɑːrtᵻkə/; nama populer: Antartika) merupakan benua yang meliputi Kutub Selatan Bumi, hampir seluruhnya terletak di Lingkar Antarktika dan dikelilingi oleh Samudra Pasifik, Samudra Atlantik dan Samudra Hindia. Dengan luas 14.0 juta km2 (5.4 juta sq mi), antarktika adalah benua terluas kelima setelah Eurasia, Afrika, Amerika Utara, dan Amerika Selatan. Sebagai perbandingan, Antarktika hampir dua kali ukuran Australia. Sekitar 98% dari Antarktika ditutupi oleh es yang rata-rata ketebalan minimal 1,9 km,[3], seluruh daratan meluas tetapi di bagian utara mencapai Semenanjung Antarktika."},
            {"Benua EROPA", "benua terbesar ke-5", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Europe_%28orthographic_projection%29.svg/480px-Europe_%28orthographic_projection%29.svg.png", "Eropa secara geologis, dan geografis adalah sebuah semenanjung atau anak benua (jazirah). Pemisahannya sebagai benua lebih dikarenakan oleh perbedaan budaya. Batas utara adalah Samudera Arktik, di barat adalah Samudera Atlantik, dan di selatan dibatasi oleh Laut Tengah. Batas timurnya masih belum jelas karena pemisahan benua ini sendiri diawali oleh faktor kebudayaan. Batas yang sering dipakai sebagai batas benua Eropa, dan Asia adalah Pegunungan Ural, dan Laut Kaspia.\\nBenua ini adalah benua terkecil kedua setelah Australia dengan luas 10.180.000 km² sedangkan bila dihitung dari populasinya, benua ini terletak di urutan ketiga dengan populasi terbanyak (di bawah Asia, dan Afrika) dengan 742,5 juta jiwa pada tahun 2013 atau sama dengan seperdelapan penduduk dunia."},
            {"Benua AUSTRALIA", "benua terbesar ke-6", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Australia_with_AAT_%28orthographic_projection%29.svg/481px-Australia_with_AAT_%28orthographic_projection%29.svg.png", "Australia, resminya Persemakmuran Australia, adalah sebuah negara di belahan selatan yang terdiri dari daratan utama benua Australia, Pulau Tasmania, dan berbagai pulau kecil di Samudra Hindia, dan Samudra Pasifik.[C 1] Negara-negara yang bertetangga dengannya adalah Indonesia, Timor Leste, dan Papua Nugini di utara; Kepulauan Solomon, Vanuatu, dan Kaledonia Baru di timur-laut; dan Selandia Baru di tenggara.\\nKira-kira 40.000 tahun sebelum pendudukan bangsa Eropa pada akhir abad ke-18, Australia telah dihuni oleh Aborigin,[2] yang menggunakan salah satu dari 250 kelompok bahasa.[3][4]"}
    };

    public static ArrayList<President> getListData(){
        President president = null;
        ArrayList<President> list = new ArrayList<>();
        for (int i = 0; i<data.length; i++){
            president = new President();
            president.setName(data[i][0]);
            president.setRemarks(data[i][1]);
            president.setPhoto(data[i][2]);
            president.setDescription(data[i][3]);

            list.add(president);
        }
        return list;
    }
}
